name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      image-name: jsfrnc/x-ray-ecs-daemon

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Get current tags
      id: gen_tags
      run: |
        if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
          TAGS='["user/image:latest","user/image:'${GITHUB_REF/refs\/tags\//}'"]'
        else
          TAGS='["user/image:latest"]'
        fi
        echo '::set-output name=tags::'$TAGS

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ fromJson(steps.gen_tags.outputs.tags) }}