name: Docker Image CI

on:
  push:
    tags:
      - '*'
    

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      image-name: jsfrnc/x-ray-ecs-daemon

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Get current tag
      id: tag
      run: |
        echo "::set-output name=version_tag::${GITHUB_REF/refs\/tags\//}"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.image-name }}:${{ steps.tag.outputs.version_tag }}
      
    - name: Docker Push
      run: docker push ${{ env.image-name }}:${{ steps.tag.outputs.version_tag }}