name: Docker Image CI

on:
  push:
    tags:
      - 'v*'
    

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      image-name: jsfrnc/x-ray-ecs-daemon

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Get current tags
      id: gen_tags
      run: |
        if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
          TAGS='["user/image:latest","user/image:'${GITHUB_REF/refs\/tags\//}'"]'
        else
          TAGS='["user/image:latest"]'
        fi
        echo '::set-output name=tags::'$TAGS

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.image-name }}:${{ fromJson(steps.gen_tags.outputs.tags) }}
      
    - name: Docker Push
      run: docker push ${{ env.image-name }}:${{ fromJson(steps.gen_tags.outputs.tags) }}